apiVersion: v1
kind: Service
metadata:
  name: h2b-mw-service
  labels:
    app: h2b-mw-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: h2b-mw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2b-mw
spec:
  selector:
    matchLabels:
      app: h2b-mw
  replicas: 1
  template:
    metadata:
      labels:
        app: h2b-mw
    spec: 
      containers:
        - image: pvb1/tsys-h2b-mw:latest
          name: h2b-mw
          ports:
            - containerPort: 3000
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: h2b-mw-api
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: h2b-mw.c-2fed325.kyma.shoot.live.k8s-hana.ondemand.com
    name: h2b-mw-service
    port: 3000